services:
  ntfy:
    image: binwiederhier/ntfy
    restart: unless-stopped
    environment:
      # NTFY_BASE_URL: https://ntfy.muitagente.com
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
    volumes:
      - ./ntfy:/var/lib/ntfy
    ports:
      - 8001:80
    command: serve