services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: uid:gid
    group_add:
      - '105'
    network_mode: 'host'
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /docker-data/media:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    #environment:
    #  - JELLYFIN_PublishedServerUrl=https://jellyfin.muitagente.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
volumes:
  jellyfin-config:
  jellyfin-cache: